-- MySQL Script generated by MySQL Workbench
-- qua 15 jul 2020 21:36:29 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `descricao_UNIQUE` (`descricao` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(20) NOT NULL COMMENT 'Coluna unica para gravar o CNPJ ou documento de empresas estrangeiras',
  `nome_empresa` VARCHAR(45) NULL,
  `codigo_postal` VARCHAR(10) NULL,
  `codigo_pais` INT NULL,
  `estado` VARCHAR(20) NULL,
  `cidade` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `numero` VARCHAR(10) NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) ,
  INDEX `fk_empresa_categoria1_idx` (`categoria_id` ASC) ,
  CONSTRAINT `fk_empresa_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` INT UNSIGNED NULL,
  `senha` VARCHAR(100) NOT NULL,
  `perfil` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuario_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario_empresa` (
  `usuario_id` INT NOT NULL,
  `empresa_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `empresa_id`),
  INDEX `fk_usuario_empresa_empresa1_idx` (`empresa_id` ASC) ,
  CONSTRAINT `fk_usuario_empresa_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_empresa_empresa1`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `integracoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integracoes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `sistema` INT NULL,
  `chave` VARCHAR(20) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `chave_UNIQUE` (`chave` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contrato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inicio` DATE NOT NULL,
  `final` DATE NOT NULL,
  `valor` DOUBLE NULL,
  `horas` INT NULL,
  `horas_contabilizadas` INT NULL,
  `empresa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contrato_empresa1_idx` (`empresa_id` ASC) ,
  CONSTRAINT `fk_contrato_empresa1`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contrato_integracao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contrato_integracao` (
  `contrato_id` INT NOT NULL,
  `integracoes_id` BIGINT NOT NULL,
  INDEX `fk_empresa_integracao_contrato1_idx` (`contrato_id` ASC) ,
  INDEX `fk_empresa_integracao_integracoes1_idx` (`integracoes_id` ASC) ,
  PRIMARY KEY (`contrato_id`, `integracoes_id`),
  CONSTRAINT `fk_empresa_integracao_contrato1`
    FOREIGN KEY (`contrato_id`)
    REFERENCES `contrato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresa_integracao_integracoes1`
    FOREIGN KEY (`integracoes_id`)
    REFERENCES `integracoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `relatorios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relatorios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `versao` INT NOT NULL,
  `documento` BLOB NOT NULL,
  `contrato_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_relatorios_contrato1_idx` (`contrato_id` ASC) ,
  CONSTRAINT `fk_relatorios_contrato1`
    FOREIGN KEY (`contrato_id`)
    REFERENCES `contrato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
