-- MySQL Script generated by MySQL Workbench
-- qui 23 jul 2020 21:10:45 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE=
'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
;

-- -----------------------------------------------------
-- Schema normas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `categoria_norma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categoria_norma`(
  `id`        INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
PRIMARY KEY(`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipo_norma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipo_norma`(
  `id`        INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
PRIMARY KEY(`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `norma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `norma` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `norma` LONGTEXT NULL,
  `categoria_norma_id` INT NOT NULL,
  `tipo_norma_id` INT NOT NULL,
  PRIMARY KEY (`id`), INDEX `fk_norma_categoria_norma_idx`(`categoria_norma_id` ASC),
INDEX `fk_norma_tipo_norma1_idx`(`tipo_norma_id` ASC),
CONSTRAINT `fk_norma_categoria_norma`
FOREIGN KEY(`categoria_norma_id`)
REFERENCES `categoria_norma`(`id`)
  ON
DELETE NO ACTION ON
UPDATE NO ACTION,
CONSTRAINT `fk_norma_tipo_norma1`
FOREIGN KEY(`tipo_norma_id`)
REFERENCES `tipo_norma`(`id`)
  ON
DELETE NO ACTION ON
UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `documentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `versao` INT NULL,
  `documento` BLOB NOT NULL,
  `norma_id` INT NOT NULL,
  PRIMARY KEY (`id`),
UNIQUE INDEX `versao_UNIQUE`(`versao` ASC),
INDEX `fk_documentos_norma1_idx`(`norma_id` ASC),
CONSTRAINT `fk_documentos_norma1`
FOREIGN KEY(`norma_id`)
REFERENCES `norma`(`id`)
  ON
DELETE NO ACTION ON
UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
